// PRODUCTS:

export const GET_PRODUCTS = "GET_PRODUCTS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const FILTER_PRICE = "FILTER_PRICE";


